# Generated by Django 5.1 on 2024-09-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prevencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PruebaDiagnostica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(default='Descripción pendiente')),
            ],
        ),
        migrations.CreateModel(
            name='Sintoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tratamiento_recomendado', models.TextField(blank=True)),
                ('prevenciones', models.ManyToManyField(to='mascotas.prevencion')),
                ('pruebas_diagnosticas', models.ManyToManyField(to='mascotas.pruebadiagnostica')),
                ('sintomas', models.ManyToManyField(to='mascotas.sintoma')),
            ],
        ),
        migrations.AddField(
            model_name='pruebadiagnostica',
            name='sintomas',
            field=models.ManyToManyField(to='mascotas.sintoma'),
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('propietario', models.CharField(max_length=100)),
                ('tratamiento', models.TextField(blank=True)),
                ('enfermedades', models.ManyToManyField(to='mascotas.enfermedad')),
                ('sintomas', models.ManyToManyField(blank=True, to='mascotas.sintoma')),
            ],
        ),
    ]
