# Generated by Django 5.1 on 2024-09-12 01:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='examen_sangre',
            field=models.FileField(blank=True, null=True, upload_to='examenes_sangre/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Examen de Sangre (PDF)'),
        ),
    ]
