# Generated by Django 5.1 on 2024-09-13 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_mascota_examen_sangre'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='direccion',
            field=models.TextField(default='Dirección no especificada'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='telefono',
            field=models.CharField(default='No especificado', max_length=15),
        ),
    ]
