# Generated by Django 5.1 on 2024-09-13 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0003_mascota_direccion_mascota_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenMascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('archivo_pdf', models.FileField(upload_to='examenes_mascotas/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='mascotas.mascota')),
            ],
        ),
    ]
