# Generated by Django 5.1 on 2024-09-18 22:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0005_pdfdocument_alter_mascota_examen_sangre_tratamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamiento',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
