# Generated by Django 5.1 on 2024-09-07 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PROGRAMADA', max_length=20)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecordatorioCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recordatorio', models.DateTimeField()),
                ('enviado', models.BooleanField(default=False)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to='citas.cita')),
            ],
        ),
    ]
