# Generated by Django 5.1 on 2024-11-04 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ['-fecha_hora']},
        ),
        migrations.DeleteModel(
            name='RecordatorioCita',
        ),
    ]
